# - name: Installing Roboshop project
#   hosts: "{{component}}"
#   become: yes
#   roles:
#   - "{{component}}"

- name: Installing Roboshop project
  hosts: "{{component}}"
  become: yes
  roles:
  - "{{component}}"